"""empty message

Revision ID: db5294663e41
Revises: d35cc55f86c8
Create Date: 2018-07-03 01:11:11.077145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5294663e41'
down_revision = 'd35cc55f86c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'RideOffer', ['ride_offer_id'], ['ride_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
